/**
 * Tiled 맵 JSON의 tilesets[].name → public/tilesets/ 에 복사해 둔 이미지 파일명(공백/특수문자 제거) 매핑.
 * Tiled가 저장한 "image" 경로는 사용자의 로컬 에셋 폴더(c:/PersonalProject/...) 를 가리키고 있어
 * 브라우저가 직접 로드할 수 없으므로, 여기서 이름으로 매칭해 public/tilesets/ 안의 사본을 대신 로드한다.
 *
 * 주의: 값(파일명)은 Windows의 대소문자 무시 파일 시스템에서 서로 충돌하면 안 된다. 예를 들어 Mixel의
 * "Bushes"(→Bushes.png)와 Fantasy Farm의 "bushes"는 소문자로 같아지므로, 후자를 "farm_bushes"로 매핑한다.
 */
export const TILED_TILESET_MANIFEST = {
  Ruins: "Ruins",
  Bushes: "Bushes",
  "Ground Tileset": "Ground_Tileset",
  Mushrooms: "Mushrooms",
  "Nature Details": "Nature_Details",
  Rocks: "Rocks",
  "Tree Stumps and Logs": "Tree_Stumps_and_Logs",
  Trees: "Trees",
  WaterTileset: "WaterTileset",
  house1: "house1",
  house2: "house2",
  house3: "house3",
  ground_grass_details: "ground_grass_details",
  exterior: "exterior",
  house_details: "house_details",
  Interior: "Interior",
  walls_floor: "walls_floor",
  TopDownHouse_DoorsAndWindows: "TopDownHouse_DoorsAndWindows",
  TopDownHouse_FloorsAndWalls: "TopDownHouse_FloorsAndWalls",
  TopDownHouse_FloorsAndWalls_OpenDoors: "TopDownHouse_FloorsAndWalls_OpenDoors",
  TopDownHouse_FurnitureState1: "TopDownHouse_FurnitureState1",
  TopDownHouse_FurnitureState2: "TopDownHouse_FurnitureState2",
  TopDownHouse_SmallItems: "TopDownHouse_SmallItems",
  "TX Plant": "TX_Plant",
  "TX Props": "TX_Props",
  "TX Struct": "TX_Struct",
  "TX Tileset Grass": "TX_Tileset_Grass",
  "TX Tileset Stone Ground": "TX_Tileset_Stone_Ground",
  "TX Tileset Wall": "TX_Tileset_Wall",
  town_multi_v002: "town_multi_v002",
  town_dark: "town_dark",
  collision: "collision",
  town_doortransparent: "town_doortransparent",
  town_corner: "town_corner",
  "32x32 first tileset": "32x32_first_tileset",
  HighTilesSheet: "HighTilesSheet",
  BasicTiles: "BasicTiles",
  DarkerBasicTiles: "DarkerBasicTiles",
  DarkerHighTilesSheet: "DarkerHighTilesSheet",
  "TX Plant Snow": "TX_Plant_Snow",
  SnowHighTilesSheet: "SnowHighTilesSheet",
  SnowBasicTiles: "SnowBasicTiles",
  houseDoors: "houseDoors",
  Cyberpunk_City_Doors_Windows_Signs: "Cyberpunk_City_Doors_Windows_Signs",
  Cyberpunk_City_Props: "Cyberpunk_City_Props",
  Cyberpunk_City_Tiles_Fences: "Cyberpunk_City_Tiles_Fences",
  Crops: "Crops",
  fence: "fence",
  flowers: "flowers",
  stones: "stones",
  decor_plants: "decor_plants",
  bushes: "farm_bushes",
  farm_tile: "farm_tile",
  "tiles-fence-32x32": "tiles-fence-32x32",
  "tiles-grass-32x32": "tiles-grass-32x32",
  "tiles-roof-thatch-32x32": "tiles-roof-thatch-32x32",
  "tiles-roof-wood-32x32": "tiles-roof-wood-32x32",
  "tiles-soil-32x32": "tiles-soil-32x32",
  "tiles-wall-32x32": "tiles-wall-32x32",
  "tiles-water-32x32": "tiles-water-32x32",
  "tiles-window-32x32": "tiles-window-32x32",
  "SIMPLE CITY 32X32": "SIMPLE_CITY_32X32",
  "tiles-door-32x32": "tiles-door-32x32",
};
